name: CI
on: [push, pull_request]
jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0, head]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rubocop

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0, head]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake spec
